aws_dbt_snowflake_project:
  outputs:
    dev:
      account: KHHAFCK-VW54502
      database: AIRBNB
      password: Brocklesnar@1108
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: NIKHILLLL1145
      warehouse: COMPUTE_WH
  target: dev
